name: yesod-page-cursor
version: 2.0.0.5
github: "freckle/yesod-page-cursor"
license: MIT
author: Freckle Engineering
maintainer: engineering@freckle.com
copyright: "2020 Renaissance Learning Inc"

extra-source-files:
  - README.md
  - ChangeLog.md

description: Cursor based pagination for Yesod

dependencies:
  - aeson < 1.6
  - base >= 4.7 && < 5
  - bytestring < 0.12
  - http-link-header < 1.3
  - text >= 1.2.3.2
  - unliftio
  - yesod-core

library:
  source-dirs: src
  dependencies:
    - containers
    - network-uri < 2.8

tests:
  yesod-page-cursor-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - hspec-expectations-lifted
      - http-types
      - lens < 5.1
      - lens-aeson
      - monad-logger
      - mtl
      - persistent < 2.13
      - persistent-sqlite < 2.12
      - persistent-template < 2.10
      - scientific
      - time < 1.12
      - unliftio-core < 0.3
      - wai-extra < 3.2
      - yesod
      - yesod-page-cursor
      - yesod-test
