name: yesod-page-cursor
version: 0.0.0.0
github: "eborden/yesod-page-cursor"
license: BSD3
author: "Evan Rutledge Borden"
maintainer: "evan@evan-borden.com"
copyright: "2019 Evan Rutledge Borden"

extra-source-files:
- README.md
- ChangeLog.md

description: Cursor based pagination for Yesod

dependencies:
- aeson
- base >= 4.7 && < 5
- base64-bytestring
- bytestring
- free
- persistent
- text
- unliftio
- yesod-core

library:
  source-dirs: src
  dependencies:
  - containers

tests:
  yesod-page-cursor-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - http-types
    - lens
    - lens-aeson
    - monad-logger
    - mtl
    - persistent
    - persistent-sqlite
    - persistent-template
    - scientific
    - time
    - wai-extra
    - yesod
    - yesod-page-cursor
    - yesod-test
